<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RequestItem extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|unique:Categories',
            'price' =>'required' ,
            'id_item'  => 'required' ,
            'location'  => 'required|string',
            'description' => 'required|String' ,
            'status' => 'required',
            'price_discount' => 'required'

        ];
    }
    public function messages()
    {
        return [
            'name.required' => 'Tha name is requerd'

        ]; // TODO: Change the autogenerated stub
    }
}
